;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-slash
        electric-newline-and-maybe-indent
        end-of-buffer
        kill-region
        upcase-region
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        ace-jump-mode
        fill-paragraph
        reindent-then-newline-and-indent
        sgml-slash
        yas/expand
        ))
